/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mutter_packageparser_PackageParser */

#ifndef _Included_com_mutter_packageparser_PackageParser
#define _Included_com_mutter_packageparser_PackageParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mutter_packageparser_PackageParser
 * Method:    dumpPackageInfo
 * Signature: (Ljava/lang/String;)Lcom/mutter/packageparser/PackageInfo;
 */
JNIEXPORT jobject JNICALL Java_com_mutter_packageparser_PackageParser_dumpPackageInfo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
